# This workflow will push an html file to Amazon S3

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: Deploy to Amazon S3

jobs:
  deploy:
    name: Deploy to AWS S3
    runs-on: windows-latest
    environment: production

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Copy file S3 bucket website
      run: |
        aws s3 cp index.html s3://card-prices-data-lake --acl public-read
